POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "sanzeliseo03@gmail.com",
  "username": "elito_magic",
  "password": "StrongPassword123@"
}

### Loggin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "sanzeliseo03@gmail.com",
  "password": "StrongPassword123@"
}

### users
