POST http://localhost:8080/api/follower/follow/3dcc1ce4-d8a2-4cbb-989e-e64cbe7b77e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNmQ1YmY4MC0zODBmLTRkNWQtYTc0NS1lYzFlMGVjMWI4OTAiLCJpYXQiOjE3MjIzNDE4MjYsImV4cCI6MTcyMjQyODIyNn0.VluLLbRecE5C-XjB3YYJpwduFIsEQeCdCY75vMlOR7g

###