name: Check Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Postgres Secrets
      run: |
        echo "POSTGRES_DB is set"
        echo "POSTGRES_USER is set"
        echo "POSTGRES_PASSWORD is set"
      env:
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Print AWS Secrets
      run: |
        echo "AWS_ACCESS_KEY_ID is set"
        echo "AWS_SECRET_ACCESS_KEY is set"
        echo "AWS_REGION is set"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
