name: Check Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    environment: twitter
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print AWS_REGION
      run: |
        echo "AWS_REGION is: ${{ secrets.AWS_REGION }}"
